apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: photosafe

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-init.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml

images:
  - name: ghcr.io/OWNER/photosafe-backend
    newName: ghcr.io/jmelloy/photosafe-backend
    newTag: latest
  - name: ghcr.io/OWNER/photosafe-frontend
    newName: ghcr.io/jmelloy/photosafe-frontend
    newTag: latest
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: kustomize
