apiVersion: v1
kind: Secret
metadata:
    name: photosafe-secrets
    namespace: photosafe
    labels:
        app.kubernetes.io/name: photosafe
        app.kubernetes.io/part-of: photosafe
type: Opaque
stringData:
    #ENC[AES256_GCM,data:LxsBfMNLnrQTZDANWLRtQ4ugC/DQM2OOhl9gASU+4uQzhLHtHxv29Fn7VXO1Vpuk2CY=,iv:N2n3H4FvCkL2q1RIck6oteYIVBbBUPkR054Vyvor/KY=,tag:MCVdAm3uZOoUS8OIoHauHQ==,type:comment]
    #ENC[AES256_GCM,data:GT0+GWZkaKfUHXsqig7Jyuv10fzV9tskO8k6CI3xHMVXEprVzXMntH5Kbey2+ytknXtTpoPiXYmDJr4UTu1zui/66w==,iv:WIaNTaukgbfZAYvf+5xXxErOaxG6Cs71kd9rpJnkxEw=,tag:BBFYSbLGvGRTAJY3GwyydQ==,type:comment]
    #ENC[AES256_GCM,data:UpoJj2SeCWO3BiJ6l+ecyYkkFdurKi/a1T9C2OMFcxhq/0s5296TkldRiD7VwWb7AhBOaW3xd+RbD+2Sbdszxjcc,iv:6nFsmFQQf84D80kKx2vLv4b9iBb8ON/AaAoRpJQyWBs=,tag:bPirwnqqcdHZQd1t6DXOwg==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:WJx5/fpSpzf7GbkAOp/6vgyAU2DsZeb23jvTEQ==,iv:YQnDBQIEKp/qzBLFEkT2XxnOGcPzm3xRrcQNmOBSMzQ=,tag:g8Sg5kMh+JdWULx0PVTT5g==,type:str]
    PHOTOSAFE_PASSWORD: ENC[AES256_GCM,data:6XorqltW10NEto15WH+GFSl3ruQEiT7C,iv:PzZqlxj5vlIzoMnjnkCAhbJBqxo7oBJe+mcDcl1MCEs=,tag:FxFwwFRvnlihLtIM7BiFaA==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:mWBw6SrLKDHUwygzAAK5ZGhUyMHGHGfzPQbGBftwH6uKGB0TwmhlDVZcTxpF9KzNTvTengGzHPceh7t6fEIExw==,iv:S7Da4XKPIdgrC5X5c5oBMuELrpLYAP2Q0KC/pzPJa6s=,tag:NNLyOSUr0F8d16oQ+9NQmA==,type:str]
    #ENC[AES256_GCM,data:XgmiPGhthd3C6a50V0LoliBhs+xSqOxaD02bSld8Kg==,iv:YzakKFHcZ7meA+O5/5Z55KGZxH3T027ZdrbBPHeuO6I=,tag:3wnsbePJ32ZtvED2CwfbVg==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:lLMmjGJ3wY+59cQTn7wTFetxg08=,iv:gwCnbrnN/eQudUmXJTisrbJnMJqFxgSo4m+IizBDCBI=,tag:iMIKWX0IEwHUDwJfg482lg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:h4ra4mlH8vxNLanhDrclvpgpgQcJcOApVLiimLt6SIUtk6riXP1MHQ==,iv:Ri3LT3chdx0yWhAeuNnIGaerSYBIO6wsV/AQ+ZCAn7o=,tag:xrhi3w/O5lGBOzu2X1CbEw==,type:str]
    #ENC[AES256_GCM,data:Js7AQQthDi4FMFjxkGOyXEx69UCWVhWV3gMTv7UsqpyaZk2WyHxQW6RPmw==,iv:B5/VpjamWuEvMSjHvy7HErljjLfL9zYWDlIAdxCXSOM=,tag:r9XftaZM8VE3GB8973o4Kg==,type:comment]
    APPLE_CREDENTIALS_ENCRYPTION_KEY: ENC[AES256_GCM,data:FNN+Hm6DBN3VxGN+1fV9kBI3j4pYdip+j7cf5QYsiSwUSv5tNrix7KmzXWo=,iv:sjwZlxF9teylCJNBIozMdyZaVkabLTpWhq8rGQ6u0zg=,tag:6nx5Z1Ayf1/MP16er2OQGA==,type:str]
sops:
    age:
        - recipient: age1k58frs2xulq70rvttn50rkegf9udexdz4ejfmj772ltqqelm03ssendps6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUlJtazlwQWFXTVZraVhC
            TkZ3OW5YWGNNQkVidTRoNkVETFNlaUNrZnl3ClNadFhpTXYweVdDbFNxTk5MM05U
            VE5UcXRaS2ZxNXllelFXd0U2MDR2eDgKLS0tIGY3bTQ2Q0J1Z3ZUbXlDUTFOTGx6
            TDUwSThMNU9nWWkrTTFMK3FiWUt3Vm8KOGUDi1xkXolVHKslF/bYy3sUXdm6mrwA
            jVbvEl6+ip3NYmm2BNJr3NY3iseUNmJZdXJQQ7K4oV3en2IpG1j4sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T18:06:53Z"
    mac: ENC[AES256_GCM,data:E9lGqcLSXd2LDC/HPGklDrnkrrvTPbhJHa2lZihaCjQ4+br86MN1BiQifrgTydFMgCZ+OG2dIycvPq4KE0nxnmxBSsYPCSkNnAXkE8Wg8oaX64+RIOfKUG69krV3pBp81KOf5UL0gGOEhowJANXjxhSDIPXbL5ePbQDw+v5kJGM=,iv:pkyI2G++KHFt4bWCUDJHyNyIrR0+MZKnrvfY6CmTE8o=,tag:4Yp0v/QtgEDrTrwVDGx0eA==,type:str]
    encrypted_regex: ^stringData$
    version: 3.11.0
